CREATE TABLE CITIES(
    CID int NOT NULL,
    CITY VARCHAR(20),
    STATE VARCHAR(20),
    PRIMARY KEY (CID)
);

CREATE TABLE WAREHOUSES(
    WID int NOT NULL,
    WNAME VARCHAR(30),
    LOCATION VARCHAR(20),
    EXTRA_CONTEXT json,
    PRIMARY KEY (WID)
);

CREATE TABLE STORES(
    SID int NOT NULL,
    STORE_NAME VARCHAR(20),
    LOCATION_CITY VARCHAR(20),
    PRIMARY KEY (SID)
);

CREATE TABLE CUSTOMER(
    CNO int NOT NULL, 
    CNAME VARCHAR(50),
    ADDR VARCHAR(50),
    CU_CITY VARCHAR(20),
    PRIMARY KEY (CNO)
);

CREATE TABLE ORDERS(
    ONO int NOT NULL,
    ODATE DATE,
    PRIMARY KEY (ONO)
);

CREATE TABLE ITEMS(
    ITEMNO int NOT NULL,
    DESCRIPTION TEXT,
    WEIGHT DECIMAL(5,2),
    COST DECIMAL(5,2),
    PRIMARY KEY (ITEMNO)
); 

ALTER TABLE WAREHOUSES
ADD CID int FOREIGNKEY REFERENCES CITIES (CID)

ALTER TABLE STORES
ADD WID int FOREIGNKEY REFERENCES WAREHOUSES (WID)

ALTER TABLE ORDERS
ADD CNO int FOREIGNKEY REFERENCES CUSTOMER (CNO)

CREATE TABLE ITEMSORDERS(
    IOID int NOT NULL,
    ITEMNO int,
    ONO int,
    PRIMARY KEY (IOID),
    FOREIGN KEY (ITEMNO) REFERENCES ITEMS (ITEMNO),
    FOREIGN KEY (ONO) REFERENCES ORDERS (ONO)
); 

CREATE TABLE STORESITEMS(
    SIID int NOT NULL,
    SID int,
    ITEMNO int,
    PRIMARY KEY (SIID),
    FOREIGN KEY (ITEMNO) REFERENCES ITEMS (ITEMNO),
    FOREIGN KEY (SID) REFERENCES STORES (SID)
); 

